version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      target: ${ENVIRONMENT}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    depends_on:
      - db
    environment:
      - Spotify__ClientId=${SPOTIFY_CLIENT_ID}
      - Spotify__ClientSecret=${SPOTIFY_CLIENT_SECRET}
      - Spotify__RedirectUri=${SPOTIFY_REDIRECT_URI}
      - Spotify__Scope=${SPOTIFY_SCOPE}
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
    volumes:
      - /var/keys:/app/keys  # Mount /var/keys on the host to /app/keys in the container
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
